project:
  type: book
  post-render: 
    - quarto render --profile slides

execute:
  freeze: auto
  echo: true

format:
  html:
    theme: 
      - default
      - custom.scss
    toc-depth: 2
    notebook-links: global
    number-sections: false

comments:
  hypothesis: true

book:
  repo-url: "https://github.com/munch-group/y-haplo-assignment"
  repo-actions: [edit, issue, source]  
  # project title
  title: "Y haplogroup assignment"
  # your name
  author: "Kasper Munch"  
  chapters:
    # your font page:
    - index.qmd
    # - workflow.py
    # - part: "Notebooks"
    #   chapters: 
    #   # your jupyter notebooks:
    #   - notebooks/01_weather.ipynb
    #   - notebooks/02_interaction.ipynb
    # - part: "Memos and docs"
    #   chapters: 
    #   # your memos, reports, manuscripts, documentation:
    #   - docs/project_diary.qmd
    #   - docs/memo_on_something.qmd
    #   - docs/howto_something.qmd
    # - part: "Reports"
    #   chapters: 
    #   # your reports, manuscripts, documentation:
    #   - reports/manuscript.qmd
    #   - reports/supplementary.qmd
    # - part: "Tables"
    #   chapters: 
    #   # your csv files rendered as tables
    #   - tables/data_table.qmd
    #   - tables/result_table.qmd      
    # - part: "Slides"
    #   chapters:
    #   # markdown slides
    #   # (the same files must be listed _quarto-slides.yml to render as slides)
    #   - slides/slides.qmd 
    #   - slides/suppl_slides.qmd

bibliography: references.bib
